unit UTestUfrmAbastecimentos;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Vcl.Buttons, FireDAC.DApt.Intf, FireDAC.Stan.Param,
  System.Classes, Vcl.ExtCtrls, Vcl.StdCtrls, FireDAC.DatS, Vcl.Grids, UfrmBase,
  Vcl.Graphics, FireDAC.Comp.Client,  Vcl.DBCtrls, Winapi.Windows,
  System.Variants,  Winapi.Messages,
  Vcl.Dialogs, FireDAC.DApt, Vcl.Forms, System.SysUtils, Data.DB, Vcl.Controls, Vcl.Mask,
  FireDAC.Comp.DataSet, Vcl.DBGrids, UfrmAbastecimentos;

type
  // Test methods for class TfrmAbastecimentos

  TestTfrmAbastecimentos = class(TTestCase)
  strict private
    FfrmAbastecimentos: TfrmAbastecimentos;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCalculoImposto;
  end;

implementation

procedure TestTfrmAbastecimentos.SetUp;
begin
  FfrmAbastecimentos := TfrmAbastecimentos.Create;
end;

procedure TestTfrmAbastecimentos.TearDown;
begin
  FfrmAbastecimentos.Free;
  FfrmAbastecimentos := nil;
end;

procedure TestTfrmAbastecimentos.TestCalculoImposto;
var
  ReturnValue: Double;
  valor: Double;
begin
  valor := 1000;
  // TODO: Setup method call parameters
  ReturnValue := FfrmAbastecimentos.CalculoImposto(valor);
  // TODO: Validate method results
  CheckEquals(130, ReturnValue, 'Falha ao testar a função CalcularValorImposto!');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTfrmAbastecimentos.Suite);
end.

